## Predicting Antibiotic Resistance in Salmonella enteriditis Using Isolate Data

## Introduction
> Antibiotic resistance is a pressing public health issue with widespread economic consequences. As bacterial pathogens like *Salmonella enteriditis* develop resistance to common antibiotics, treating infections becomes increasingly challenging, leading to higher healthcare costs and greater risks for affected populations. *Salmonella enteriditis*, a significant cause of foodborne illness globally, has exhibited growing resistance to antibiotics, complicating treatment and control efforts.
>
> This project aims to develop a predictive model that forecasts antibiotic resistance trends in *Salmonella enteriditis* by analyzing isolate data. Leveraging machine learning techniques, the model will utilize antibiotic susceptibility testing (AST) results along with specimen metadata, such as the year of collection and geographic region, to identify emerging resistance patterns. These predictions are intended to inform public health strategies, optimize resource allocation, and ultimately improve food safety measures.

## Project Objectives
> - **Forecast Antibiotic Resistance**: Develop a model that predicts resistance patterns in *Salmonella enteriditis* using AST results and metadata, enabling timely interventions.
> - **Support Public Health and Food Safety**: Provide actionable insights to healthcare providers and policymakers that can guide decisions on resource allocation and risk management.
> - **Explore Data-Driven Solutions**: Apply data science techniques, including data wrangling, exploratory data analysis, and machine learning, to address a real-world issue with far-reaching implications.

## Data Source
>The dataset used in this project is sourced from the CDC National Antimicrobial Resistance Monitoring System (NARMS), providing comprehensive surveillance data on antimicrobial resistance in foodborne pathogens. This dataset includes detailed information on antibiotic susceptibility testing and resistance determinants, making it well-suited for predictive modeling of resistance trends.

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Load the Excel file
file_path = 'salmonella_enteritidis_isolate_data.csv'  # Replace with your file path
salmonella_isolate_df = pd.read_csv(file_path)

C:\Users\rgarl\AppData\Local\Temp\ipykernel_34208\1496524901.py:3: DtypeWarning: Columns (60,62,108,110) have mixed types. Specify dtype option on import or set low_memory=False.
  salmonella_isolate_df = pd.read_csv(file_path)

In [3]:
# Display the first few rows of the dataset to understand its structure
salmonella_isolate_df.head()

,Specimen ID,Genus,Species,Serotype,Data Year,Region Name,Age Group,Specimen Source,AMI Equiv,AMI Rslt,...,TEL Concl,TEL ConclPred,TET Equiv,TET Rslt,TET Concl,TET ConclPred,TIO Equiv,TIO Rslt,TIO Concl,TIO ConclPred
0,AM15266,Salmonella,enterica,Enteritidis,2003,Region 5,30-39,Stool,=,1.0,...,NaN,NaN,<=,4,S,NaN,=,2.0,S,NaN
1,AM43140,Salmonella,enterica,Enteritidis,2010,Region 2,NaN,Stool,=,1.0,...,NaN,NaN,<=,4,S,NaN,=,1.0,S,NaN
2,AM04769,Salmonella,enterica,Enteritidis,1998,Region 2,30-39,Stool,<=,4.0,...,NaN,NaN,<=,4,S,NaN,<=,0.5,S,NaN
3,AM43324,Salmonella,enterica,Enteritidis,2010,Region 9,40-49,Stool,=,1.0,...,NaN,NaN,<=,4,S,NaN,=,1.0,S,NaN
4,AM29874,Salmonella,enterica,Enteritidis,2006,Region 10,NaN,Stool,=,1.0,...,NaN,NaN,<=,4,S,NaN,=,1.0,S,NaN

In [4]:
# Check for duplicates in the 'Specimen ID' column
duplicate_specimen_ids = salmonella_isolate_df[salmonella_isolate_df.duplicated(subset='Specimen ID', keep=False)]

# Count of duplicate entries
duplicate_count = duplicate_specimen_ids.shape[0]

duplicate_count

0

In [5]:
# Display all columns with 'object' data type
# This helps to identify potential categorical variables for further processing
object_columns = salmonella_isolate_df.select_dtypes(include='object').columns

# Print the names of all object-type columns
print("Object-type columns:", object_columns.tolist())

Object-type columns: ['Specimen ID', 'Genus', 'Species', 'Serotype', 'Region Name', 'Age Group', 'Specimen Source', 'AMI Equiv', 'AMI Concl', 'AMI ConclPred', 'AMP Equiv', 'AMP Concl', 'AMP ConclPred', 'ATM Equiv', 'ATM Concl', 'ATM ConclPred', 'AUG Equiv', 'AUG Concl', 'AUG ConclPred', 'AXO Equiv', 'AXO Concl', 'AXO ConclPred', 'AZM Equiv', 'AZM Concl', 'AZM ConclPred', 'CAZ Equiv', 'CAZ Concl', 'CAZ ConclPred', 'CCV Equiv', 'CCV Concl', 'CCV ConclPred', 'CEP Equiv', 'CEP Concl', 'CEP ConclPred', 'CEQ Equiv', 'CEQ Concl', 'CEQ ConclPred', 'CHL Equiv', 'CHL Concl', 'CHL ConclPred', 'CIP Equiv', 'CIP Concl', 'CIP ConclPred', 'CLI ConclPred', 'COL Equiv', 'COL Concl', 'COL ConclPred', 'COT Equiv', 'COT Concl', 'COT ConclPred', 'CTC Equiv', 'CTC Concl', 'CTC ConclPred', 'CTX Equiv', 'CTX Concl', 'CTX ConclPred', 'ERY ConclPred', 'FEP Equiv', 'FEP Concl', 'FEP ConclPred', 'FFN ConclPred', 'FIS Equiv', 'FIS Concl', 'FIS ConclPred', 'FOX Equiv', 'FOX Concl', 'FOX ConclPred', 'GEN Equiv', 'GEN Concl', 'GEN ConclPred', 'IMI Equiv', 'IMI Concl', 'IMI ConclPred', 'KAN Equiv', 'KAN Concl', 'KAN ConclPred', 'MER Equiv', 'MER Concl', 'MER ConclPred', 'NAL Equiv', 'NAL Concl', 'NAL ConclPred', 'PTZ Equiv', 'PTZ Concl', 'PTZ ConclPred', 'SMX Equiv', 'SMX Concl', 'SMX ConclPred', 'STR Equiv', 'STR Concl', 'STR ConclPred', 'TEL ConclPred', 'TET Equiv', 'TET Concl', 'TET ConclPred', 'TIO Equiv', 'TIO Concl', 'TIO ConclPred']

In [6]:
# Identify columns with all missing values (100% NaN) before removing them
# This step is crucial to eliminate any columns that do not contribute to the analysis
columns_all_missing = salmonella_isolate_df.columns[salmonella_isolate_df.isnull().all()]
columns_all_missing

Index(['CLI Equiv', 'CLI Rslt', 'CLI Concl', 'ERY Equiv', 'ERY Rslt',
       'ERY Concl', 'FFN Equiv', 'FFN Rslt', 'FFN Concl', 'TEL Equiv',
       'TEL Rslt', 'TEL Concl'],
      dtype='object')

In [7]:
# Define the list of columns to be removed 
columns_to_remove = [
    'Genus', 'Species', 'Serotype', 'CLI Equiv', 'CLI Rslt', 'CLI Concl', 'ERY Equiv', 'ERY Rslt',
    'ERY Concl', 'FFN Equiv', 'FFN Rslt', 'FFN Concl', 'TEL Equiv', 'TEL Rslt', 'TEL Concl'
]
# Remove the specified columns from the dataset
salmonella_isolate_df_cleaned = salmonella_isolate_df.drop(columns=columns_to_remove)

In [8]:
# Identify columns to remove based on suffixes
columns_to_remove_suffix = salmonella_isolate_df_cleaned.filter(regex='Equiv$|Rslt$|ConclPred$').columns.tolist()
# Remove the specified columns from the DataFrame
salmonella_isolate_df_cleaned = salmonella_isolate_df_cleaned.drop(columns=columns_to_remove_suffix)

In [9]:
# Count the number of missing values (NaN) in the 'Data Year' column
missing_values_count = salmonella_isolate_df_cleaned['Data Year'].isnull().sum()
missing_values_count

0

In [10]:
salmonella_isolate_df_cleaned['Data Year'].dtype

dtype('int64')

In [11]:
# Investigate counts of each year in the 'Data Year' column
year_counts = salmonella_isolate_df_cleaned['Data Year'].value_counts()

# Sort the counts from low to high
sorted_year_counts = year_counts.sort_index()

# Display the sorted counts
sorted_year_counts

Data Year
1996    354
1997    296
1998    245
1999    266
2000    319
2001    276
2002    337
2003    256
2004    271
2005    384
2006    412
2007    385
2008    442
2009    410
2010    513
2011    391
2012    364
2013    382
2014    438
2015    471
2016    437
2017    431
2018    441
2019    404
2020    280
2021    291
2022    422
2023    339
Name: count, dtype: int64

In [12]:
# Calculate null values in each column and print columns with missing values
null_counts = salmonella_isolate_df_cleaned.isnull().sum()
missing_values = null_counts[null_counts > 0]
missing_values

Age Group            447
Specimen Source       52
AMI Concl           5421
ATM Concl          10220
AZM Concl           5124
CAZ Concl          10220
CCV Concl          10226
CEP Concl           7908
CEQ Concl          10220
COL Concl           8923
CTC Concl          10226
CTX Concl          10220
FEP Concl          10220
FIS Concl           2349
FOX Concl           1111
IMI Concl           9946
KAN Concl           3955
MER Concl           7212
PTZ Concl          10220
SMX Concl           7908
STR Concl           1334
TIO Concl           3045
dtype: int64

In [13]:
# Impute missing values in 'Age Group' and 'Specimen Source' with the mode
# This ensures that missing categorical data is handled appropriately, maintaining the integrity of the dataset
salmonella_isolate_df_cleaned['Age Group'] = salmonella_isolate_df_cleaned['Age Group'].fillna(salmonella_isolate_df_cleaned['Age Group'].mode()[0])
salmonella_isolate_df_cleaned['Specimen Source'] = salmonella_isolate_df_cleaned['Specimen Source'].fillna(salmonella_isolate_df_cleaned['Specimen Source'].mode()[0])

In [14]:
# Drop columns with more than 90% missing values
threshold = 0.9 * len(salmonella_isolate_df_cleaned)
columns_to_drop_90_percent_missing = salmonella_isolate_df_cleaned.columns[salmonella_isolate_df_cleaned.isnull().sum() > threshold]
salmonella_isolate_df_cleaned = salmonella_isolate_df_cleaned.drop(columns=columns_to_drop_90_percent_missing)

In [15]:
# Calculate null values in each column
null_counts = salmonella_isolate_df_cleaned.isnull().sum()

# Filter to show only columns with missing values
missing_values = null_counts[null_counts > 0]

# Print column names and their corresponding missing values
for column, count in missing_values.items():
    print(f"Column: {column}, Missing Values: {count}")

Column: AMI Concl, Missing Values: 5421
Column: AZM Concl, Missing Values: 5124
Column: CEP Concl, Missing Values: 7908
Column: COL Concl, Missing Values: 8923
Column: FIS Concl, Missing Values: 2349
Column: FOX Concl, Missing Values: 1111
Column: KAN Concl, Missing Values: 3955
Column: MER Concl, Missing Values: 7212
Column: SMX Concl, Missing Values: 7908
Column: STR Concl, Missing Values: 1334
Column: TIO Concl, Missing Values: 3045

In [16]:
# Impute missing values in 'Concl' columns with 'X' to indicate missing data
# This signifies that breakpoints or epidemiological cutoff values are not available for certain tests
for col in [col for col in salmonella_isolate_df_cleaned.columns if col.endswith('Concl')]:
    salmonella_isolate_df_cleaned[col] = salmonella_isolate_df_cleaned[col].fillna('X')

In [17]:
# Get all conclusion columns from the cleaned DataFrame
concl_columns = [col for col in salmonella_isolate_df_cleaned.columns if 'Concl' in col]

# Create a copy of the DataFrame to avoid modifying the original
imputed_df = salmonella_isolate_df_cleaned.copy()

# Initialize a dictionary to hold yearly percentages for each column
yearly_percentages = {}

# Loop through each conclusion column to calculate yearly percentages
for col in concl_columns:
    # Calculate the total counts for each category per year
    total_counts = salmonella_isolate_df_cleaned.groupby('Data Year')[col].value_counts(normalize=True).unstack(fill_value=0) * 100
    
    # Store the percentages in the dictionary
    yearly_percentages[col] = total_counts

# Display the calculated yearly percentages for each conclusion column
yearly_percentages

{'AMI Concl': AMI Concl           S           X
 Data Year
 1996         7.062147   92.937853
 1997        99.662162    0.337838
 1998       100.000000    0.000000
 1999       100.000000    0.000000
 2000       100.000000    0.000000
 2001       100.000000    0.000000
 2002       100.000000    0.000000
 2003       100.000000    0.000000
 2004       100.000000    0.000000
 2005       100.000000    0.000000
 2006       100.000000    0.000000
 2007       100.000000    0.000000
 2008       100.000000    0.000000
 2009       100.000000    0.000000
 2010       100.000000    0.000000
 2011         0.000000  100.000000
 2012         0.000000  100.000000
 2013         0.000000  100.000000
 2014         0.000000  100.000000
 2015         0.000000  100.000000
 2016         0.000000  100.000000
 2017         0.000000  100.000000
 2018         0.000000  100.000000
 2019         0.000000  100.000000
 2020         0.000000  100.000000
 2021         0.000000  100.000000
 2022         0.000000  100.000000
 2023         0.000000  100.000000,
 'AMP Concl': AMP Concl         I          R          S
 Data Year
 1996       0.000000  20.621469  79.378531
 1997       0.000000  11.486486  88.513514
 1998       0.000000   6.122449  93.877551
 1999       0.000000  10.526316  89.473684
 2000       0.000000   7.523511  92.476489
 2001       0.362319   8.333333  91.304348
 2002       0.000000   6.824926  93.175074
 2003       0.000000   2.343750  97.656250
 2004       0.000000   4.059041  95.940959
 2005       0.000000   2.604167  97.395833
 2006       0.000000   4.126214  95.873786
 2007       0.000000   2.077922  97.922078
 2008       0.226244   4.072398  95.701357
 2009       0.000000   3.902439  96.097561
 2010       0.000000   2.339181  97.660819
 2011       0.000000   5.115090  94.884910
 2012       0.000000   4.120879  95.879121
 2013       0.000000   5.759162  94.240838
 2014       0.000000   3.196347  96.803653
 2015       0.000000   5.944798  94.055202
 2016       0.228833   5.263158  94.508009
 2017       0.000000   3.248260  96.751740
 2018       0.000000   1.814059  98.185941
 2019       0.000000   2.722772  97.277228
 2020       0.000000   4.285714  95.714286
 2021       0.000000   3.092784  96.907216
 2022       0.000000   3.080569  96.919431
 2023       0.000000   4.129794  95.870206,
 'AUG Concl': AUG Concl         I         R           S
 Data Year
 1996       6.779661  0.564972   92.655367
 1997       3.716216  0.000000   96.283784
 1998       0.000000  0.000000  100.000000
 1999       1.879699  0.375940   97.744361
 2000       2.507837  0.000000   97.492163
 2001       2.173913  1.086957   96.739130
 2002       1.780415  0.593472   97.626113
 2003       0.781250  0.000000   99.218750
 2004       1.476015  0.000000   98.523985
 2005       1.041667  0.781250   98.177083
 2006       0.485437  0.485437   99.029126
 2007       0.000000  0.519481   99.480519
 2008       0.452489  0.000000   99.547511
 2009       0.243902  0.000000   99.756098
 2010       0.194932  0.389864   99.415205
 2011       0.000000  0.255754   99.744246
 2012       0.274725  0.549451   99.175824
 2013       0.785340  0.000000   99.214660
 2014       0.684932  0.456621   98.858447
 2015       0.424628  0.849257   98.726115
 2016       0.228833  0.915332   98.855835
 2017       0.232019  0.464037   99.303944
 2018       0.226757  0.226757   99.546485
 2019       0.247525  0.000000   99.752475
 2020       1.071429  0.714286   98.214286
 2021       0.687285  0.343643   98.969072
 2022       0.236967  0.236967   99.526066
 2023       0.589971  0.000000   99.410029,
 'AXO Concl': AXO Concl         I         R           S
 Data Year
 1996       0.000000  0.000000  100.000000
 1997       0.000000  0.337838   99.662162
 1998       0.000000  0.000000  100.000000
 1999       0.000000  0.375940   99.624060
 2000       0.000000  0.000000  100.000000
 2001       0.362319  1.449275   98.188406
 2002       0.000000  0.000000  100.000000
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  0.260417   99.739583
 2006       0.000000  0.485437   99.514563
 2007       0.000000  0.259740   99.740260
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.000000  0.000000  100.000000
 2011       0.000000  0.255754   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.000000  0.261780   99.738220
 2014       0.000000  0.456621   99.543379
 2015       0.000000  0.212314   99.787686
 2016       0.228833  0.686499   99.084668
 2017       0.000000  0.464037   99.535963
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.247525   99.752475
 2020       0.000000  0.714286   99.285714
 2021       0.000000  0.000000  100.000000
 2022       0.000000  0.236967   99.763033
 2023       0.000000  0.000000  100.000000,
 'AZM Concl': AZM Concl         R           S           X
 Data Year
 1996       0.000000    0.000000  100.000000
 1997       0.000000    0.000000  100.000000
 1998       0.000000    0.000000  100.000000
 1999       0.000000    0.000000  100.000000
 2000       0.000000    0.000000  100.000000
 2001       0.000000    0.000000  100.000000
 2002       0.000000    0.000000  100.000000
 2003       0.000000    0.000000  100.000000
 2004       0.000000    0.000000  100.000000
 2005       0.000000    0.000000  100.000000
 2006       0.000000    0.000000  100.000000
 2007       0.000000    0.000000  100.000000
 2008       0.000000    9.502262   90.497738
 2009       0.000000    0.000000  100.000000
 2010       0.000000    0.000000  100.000000
 2011       0.000000  100.000000    0.000000
 2012       0.000000  100.000000    0.000000
 2013       0.000000  100.000000    0.000000
 2014       0.000000  100.000000    0.000000
 2015       0.212314   99.787686    0.000000
 2016       0.000000  100.000000    0.000000
 2017       0.000000  100.000000    0.000000
 2018       0.000000  100.000000    0.000000
 2019       0.000000  100.000000    0.000000
 2020       0.000000  100.000000    0.000000
 2021       0.343643   99.656357    0.000000
 2022       0.236967   99.763033    0.000000
 2023       0.000000  100.000000    0.000000,
 'CEP Concl': CEP Concl         I         R          S      X
 Data Year
 1996       3.389831  3.954802  92.655367    0.0
 1997       4.391892  1.351351  94.256757    0.0
 1998       0.816327  0.000000  99.183673    0.0
 1999       1.503759  1.879699  96.616541    0.0
 2000       1.567398  0.940439  97.492163    0.0
 2001       2.898551  1.086957  96.014493    0.0
 2002       2.670623  0.593472  96.735905    0.0
 2003       0.781250  1.171875  98.046875    0.0
 2004       0.000000  0.000000   0.000000  100.0
 2005       0.000000  0.000000   0.000000  100.0
 2006       0.000000  0.000000   0.000000  100.0
 2007       0.000000  0.000000   0.000000  100.0
 2008       0.000000  0.000000   0.000000  100.0
 2009       0.000000  0.000000   0.000000  100.0
 2010       0.000000  0.000000   0.000000  100.0
 2011       0.000000  0.000000   0.000000  100.0
 2012       0.000000  0.000000   0.000000  100.0
 2013       0.000000  0.000000   0.000000  100.0
 2014       0.000000  0.000000   0.000000  100.0
 2015       0.000000  0.000000   0.000000  100.0
 2016       0.000000  0.000000   0.000000  100.0
 2017       0.000000  0.000000   0.000000  100.0
 2018       0.000000  0.000000   0.000000  100.0
 2019       0.000000  0.000000   0.000000  100.0
 2020       0.000000  0.000000   0.000000  100.0
 2021       0.000000  0.000000   0.000000  100.0
 2022       0.000000  0.000000   0.000000  100.0
 2023       0.000000  0.000000   0.000000  100.0,
 'CHL Concl': CHL Concl         I         R           S
 Data Year
 1996       0.282486  0.000000   99.717514
 1997       1.351351  0.675676   97.972973
 1998       0.000000  0.000000  100.000000
 1999       0.000000  0.375940   99.624060
 2000       0.313480  0.000000   99.686520
 2001       1.086957  0.000000   98.913043
 2002       0.000000  0.296736   99.703264
 2003       0.390625  0.390625   99.218750
 2004       0.369004  0.369004   99.261993
 2005       0.000000  0.520833   99.479167
 2006       0.000000  0.000000  100.000000
 2007       0.779221  0.519481   98.701299
 2008       0.226244  0.452489   99.321267
 2009       0.243902  0.000000   99.756098
 2010       0.389864  0.584795   99.025341
 2011       0.255754  0.000000   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.785340  0.261780   98.952880
 2014       0.456621  1.141553   98.401826
 2015       0.636943  0.212314   99.150743
 2016       0.228833  1.601831   98.169336
 2017       1.392111  1.392111   97.215777
 2018       0.680272  0.453515   98.866213
 2019       0.742574  0.495050   98.762376
 2020       0.357143  1.071429   98.571429
 2021       0.343643  1.030928   98.625430
 2022       0.710900  0.000000   99.289100
 2023       1.474926  0.000000   98.525074,
 'CIP Concl': CIP Concl          I         R          S
 Data Year
 1996        0.282486  0.000000  99.717514
 1997        2.027027  0.000000  97.972973
 1998        2.448980  0.000000  97.551020
 1999        1.503759  0.375940  98.120301
 2000        2.194357  0.000000  97.805643
 2001        3.623188  0.000000  96.376812
 2002        3.560831  0.000000  96.439169
 2003        3.906250  0.000000  96.093750
 2004        6.273063  0.369004  93.357934
 2005        3.906250  0.000000  96.093750
 2006        7.038835  0.000000  92.961165
 2007        5.974026  0.000000  94.025974
 2008        7.239819  0.000000  92.760181
 2009        3.658537  0.000000  96.341463
 2010        4.873294  0.194932  94.931774
 2011        7.161125  0.000000  92.838875
 2012        7.967033  0.000000  92.032967
 2013        5.497382  0.000000  94.502618
 2014        7.762557  0.228311  92.009132
 2015       13.800425  0.000000  86.199575
 2016       11.670481  0.000000  88.329519
 2017       20.649652  0.000000  79.350348
 2018       22.222222  0.226757  77.551020
 2019       29.207921  0.000000  70.792079
 2020       28.928571  0.000000  71.071429
 2021       31.615120  0.343643  68.041237
 2022       37.677725  0.236967  62.085308
 2023       48.377581  0.000000  51.622419,
 'COL Concl': COL Concl          I          R           X
 Data Year
 1996        0.000000   0.000000  100.000000
 1997        0.000000   0.000000  100.000000
 1998        0.000000   0.000000  100.000000
 1999        0.000000   0.000000  100.000000
 2000        0.000000   0.000000  100.000000
 2001        0.000000   0.000000  100.000000
 2002        0.000000   0.000000  100.000000
 2003        0.000000   0.000000  100.000000
 2004        0.000000   0.000000  100.000000
 2005        0.000000   0.000000  100.000000
 2006        0.000000   0.000000  100.000000
 2007        0.000000   0.000000  100.000000
 2008        0.000000   0.000000  100.000000
 2009        0.000000   0.000000  100.000000
 2010        0.000000   0.000000  100.000000
 2011        0.000000   0.000000  100.000000
 2012        0.000000   0.000000  100.000000
 2013        0.000000   0.000000  100.000000
 2014        0.000000   0.000000  100.000000
 2015        0.000000   0.000000  100.000000
 2016        0.000000   0.228833   99.771167
 2017        0.000000   0.000000  100.000000
 2018        0.000000   0.000000  100.000000
 2019        0.247525   0.000000   99.752475
 2020       88.571429  11.428571    0.000000
 2021       78.006873  21.993127    0.000000
 2022       75.829384  24.170616    0.000000
 2023       88.790560  11.209440    0.000000,
 'COT Concl': COT Concl         R           S
 Data Year
 1996       6.497175   93.502825
 1997       1.351351   98.648649
 1998       0.816327   99.183673
 1999       0.751880   99.248120
 2000       0.000000  100.000000
 2001       0.724638   99.275362
 2002       0.593472   99.406528
 2003       0.781250   99.218750
 2004       0.000000  100.000000
 2005       0.520833   99.479167
 2006       0.485437   99.514563
 2007       1.038961   98.961039
 2008       0.904977   99.095023
 2009       0.731707   99.268293
 2010       0.974659   99.025341
 2011       0.511509   99.488491
 2012       1.098901   98.901099
 2013       0.523560   99.476440
 2014       0.456621   99.543379
 2015       1.910828   98.089172
 2016       1.144165   98.855835
 2017       0.928074   99.071926
 2018       0.226757   99.773243
 2019       0.247525   99.752475
 2020       0.000000  100.000000
 2021       0.343643   99.656357
 2022       0.236967   99.763033
 2023       0.000000  100.000000,
 'FIS Concl': FIS Concl         R          S      X
 Data Year
 1996       0.000000   0.000000  100.0
 1997       0.000000   0.000000  100.0
 1998       0.000000   0.000000  100.0
 1999       0.000000   0.000000  100.0
 2000       0.000000   0.000000  100.0
 2001       0.000000   0.000000  100.0
 2002       0.000000   0.000000  100.0
 2003       0.000000   0.000000  100.0
 2004       1.845018  98.154982    0.0
 2005       1.562500  98.437500    0.0
 2006       1.456311  98.543689    0.0
 2007       1.558442  98.441558    0.0
 2008       1.357466  98.642534    0.0
 2009       1.707317  98.292683    0.0
 2010       1.949318  98.050682    0.0
 2011       2.046036  97.953964    0.0
 2012       2.747253  97.252747    0.0
 2013       1.570681  98.429319    0.0
 2014       1.826484  98.173516    0.0
 2015       3.397028  96.602972    0.0
 2016       4.118993  95.881007    0.0
 2017       2.784223  97.215777    0.0
 2018       1.587302  98.412698    0.0
 2019       1.485149  98.514851    0.0
 2020       2.142857  97.857143    0.0
 2021       2.061856  97.938144    0.0
 2022       2.132701  97.867299    0.0
 2023       2.064897  97.935103    0.0,
 'FOX Concl': FOX Concl         I         R           S           X
 Data Year
 1996       0.000000  0.000000    5.649718   94.350282
 1997       0.337838  0.337838    9.121622   90.202703
 1998       0.000000  0.000000    0.000000  100.000000
 1999       0.000000  0.000000    0.375940   99.624060
 2000       0.000000  0.000000  100.000000    0.000000
 2001       0.724638  0.362319   98.913043    0.000000
 2002       0.296736  0.000000   99.703264    0.000000
 2003       0.000000  0.000000  100.000000    0.000000
 2004       0.000000  0.000000  100.000000    0.000000
 2005       0.000000  1.041667   98.958333    0.000000
 2006       0.000000  0.485437   99.514563    0.000000
 2007       0.259740  0.259740   99.480519    0.000000
 2008       0.452489  0.000000   99.547511    0.000000
 2009       0.000000  0.000000  100.000000    0.000000
 2010       0.194932  0.000000   99.805068    0.000000
 2011       0.511509  0.255754   99.232737    0.000000
 2012       0.549451  0.549451   98.901099    0.000000
 2013       0.261780  0.000000   99.738220    0.000000
 2014       0.000000  0.684932   99.315068    0.000000
 2015       0.636943  0.424628   98.938429    0.000000
 2016       0.228833  0.686499   99.084668    0.000000
 2017       0.232019  0.696056   99.071926    0.000000
 2018       0.000000  0.226757   99.773243    0.000000
 2019       0.495050  0.000000   99.504950    0.000000
 2020       0.357143  0.714286   98.928571    0.000000
 2021       1.030928  0.343643   98.625430    0.000000
 2022       0.000000  0.236967   99.763033    0.000000
 2023       0.294985  0.000000   99.705015    0.000000,
 'GEN Concl': GEN Concl         I         R           S
 Data Year
 1996       0.847458  4.802260   94.350282
 1997       0.000000  0.337838   99.662162
 1998       0.000000  0.408163   99.591837
 1999       0.000000  0.000000  100.000000
 2000       0.000000  0.313480   99.686520
 2001       0.000000  0.000000  100.000000
 2002       0.000000  0.296736   99.703264
 2003       0.000000  0.390625   99.609375
 2004       0.000000  0.369004   99.630996
 2005       0.000000  0.781250   99.218750
 2006       0.000000  0.242718   99.757282
 2007       0.000000  0.000000  100.000000
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.194932   99.610136
 2011       0.000000  0.511509   99.488491
 2012       0.000000  0.000000  100.000000
 2013       0.000000  0.000000  100.000000
 2014       0.456621  0.000000   99.543379
 2015       0.000000  0.424628   99.575372
 2016       0.000000  0.000000  100.000000
 2017       0.000000  0.000000  100.000000
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.000000  100.000000
 2020       0.000000  0.000000  100.000000
 2021       0.000000  0.343643   99.656357
 2022       0.000000  0.000000  100.000000
 2023       0.000000  0.000000  100.000000,
 'KAN Concl': KAN Concl         I         R           S          X
 Data Year
 1996       0.282486  0.000000   99.717514    0.00000
 1997       0.000000  0.675676   99.324324    0.00000
 1998       0.000000  0.408163   99.591837    0.00000
 1999       0.000000  0.375940   99.624060    0.00000
 2000       0.000000  0.313480   99.686520    0.00000
 2001       0.000000  0.724638   99.275362    0.00000
 2002       0.000000  0.296736   99.703264    0.00000
 2003       0.000000  0.000000  100.000000    0.00000
 2004       0.000000  0.738007   99.261993    0.00000
 2005       0.260417  0.260417   99.479167    0.00000
 2006       0.000000  0.242718   99.757282    0.00000
 2007       0.000000  0.519481   99.480519    0.00000
 2008       0.000000  0.000000  100.000000    0.00000
 2009       0.000000  0.243902   99.756098    0.00000
 2010       0.000000  0.194932   99.805068    0.00000
 2011       0.000000  0.255754   99.744246    0.00000
 2012       0.000000  0.000000  100.000000    0.00000
 2013       0.000000  0.000000   99.738220    0.26178
 2014       0.000000  0.000000    0.000000  100.00000
 2015       0.000000  0.000000    0.000000  100.00000
 2016       0.000000  0.000000    0.000000  100.00000
 2017       0.000000  0.000000    0.000000  100.00000
 2018       0.000000  0.000000    0.000000  100.00000
 2019       0.000000  0.000000    0.000000  100.00000
 2020       0.000000  0.000000    0.000000  100.00000
 2021       0.000000  0.000000    0.000000  100.00000
 2022       0.000000  0.000000    0.000000  100.00000
 2023       0.000000  0.000000    0.000000  100.00000,
 'MER Concl': MER Concl      S      X
 Data Year
 1996         0.0  100.0
 1997         0.0  100.0
 1998         0.0  100.0
 1999         0.0  100.0
 2000         0.0  100.0
 2001         0.0  100.0
 2002         0.0  100.0
 2003         0.0  100.0
 2004         0.0  100.0
 2005         0.0  100.0
 2006         0.0  100.0
 2007         0.0  100.0
 2008         0.0  100.0
 2009         0.0  100.0
 2010         0.0  100.0
 2011         0.0  100.0
 2012         0.0  100.0
 2013         0.0  100.0
 2014         0.0  100.0
 2015         0.0  100.0
 2016       100.0    0.0
 2017       100.0    0.0
 2018       100.0    0.0
 2019       100.0    0.0
 2020       100.0    0.0
 2021       100.0    0.0
 2022       100.0    0.0
 2023       100.0    0.0,
 'NAL Concl': NAL Concl          R          S
 Data Year
 1996        0.282486  99.717514
 1997        1.689189  98.310811
 1998        2.040816  97.959184
 1999        2.255639  97.744361
 2000        2.194357  97.805643
 2001        4.347826  95.652174
 2002        3.857567  96.142433
 2003        4.687500  95.312500
 2004        6.642066  93.357934
 2005        4.687500  95.312500
 2006        7.038835  92.961165
 2007        5.714286  94.285714
 2008        7.239819  92.760181
 2009        3.658537  96.341463
 2010        5.263158  94.736842
 2011        7.161125  92.838875
 2012        7.692308  92.307692
 2013        5.759162  94.240838
 2014        7.990868  92.009132
 2015       13.163482  86.836518
 2016       11.670481  88.329519
 2017       20.417633  79.582367
 2018       21.315193  78.684807
 2019       28.960396  71.039604
 2020       28.571429  71.428571
 2021       31.615120  68.384880
 2022       36.966825  63.033175
 2023       47.492625  52.507375,
 'SMX Concl': SMX Concl         R          S      X
 Data Year
 1996       8.757062  91.242938    0.0
 1997       8.783784  91.216216    0.0

In [18]:
# Filter the DataFrame for the years 2003 to 2023
salmonella_isolate_df_cleaned = salmonella_isolate_df_cleaned[salmonella_isolate_df_cleaned['Data Year'].between(2003, 2023)]

In [19]:
# Remove the specified columns from the DataFrame
columns_to_remove = [
    'AMI Concl',
    'AZM Concl',
    'CEP Concl',
    'COL Concl',
    'KAN Concl',
    'MER Concl',
    'SMX Concl',
    'TIO Concl'
]

# Drop the specified columns
salmonella_isolate_df_cleaned.drop(columns=columns_to_remove, inplace=True)

In [20]:
# Get all conclusion columns from the cleaned DataFrame
concl_columns = [col for col in salmonella_isolate_df_cleaned.columns if 'Concl' in col]

# Display all conclusion columns
concl_columns

['AMP Concl',
 'AUG Concl',
 'AXO Concl',
 'CHL Concl',
 'CIP Concl',
 'COT Concl',
 'FIS Concl',
 'FOX Concl',
 'GEN Concl',
 'NAL Concl',
 'STR Concl',
 'TET Concl']

In [21]:
# Display the calculated yearly percentages for each conclusion column
yearly_percentages = {}

# Loop through each conclusion column to calculate yearly percentages
for col in concl_columns:
    # Calculate the total counts for each category per year
    total_counts = salmonella_isolate_df_cleaned.groupby('Data Year')[col].value_counts(normalize=True).unstack(fill_value=0) * 100
    
    # Store the percentages in the dictionary
    yearly_percentages[col] = total_counts

# Display the calculated yearly percentages for each conclusion column
yearly_percentages_outputs = {col: data for col, data in yearly_percentages.items()}
yearly_percentages_outputs

{'AMP Concl': AMP Concl         I         R          S
 Data Year
 2003       0.000000  2.343750  97.656250
 2004       0.000000  4.059041  95.940959
 2005       0.000000  2.604167  97.395833
 2006       0.000000  4.126214  95.873786
 2007       0.000000  2.077922  97.922078
 2008       0.226244  4.072398  95.701357
 2009       0.000000  3.902439  96.097561
 2010       0.000000  2.339181  97.660819
 2011       0.000000  5.115090  94.884910
 2012       0.000000  4.120879  95.879121
 2013       0.000000  5.759162  94.240838
 2014       0.000000  3.196347  96.803653
 2015       0.000000  5.944798  94.055202
 2016       0.228833  5.263158  94.508009
 2017       0.000000  3.248260  96.751740
 2018       0.000000  1.814059  98.185941
 2019       0.000000  2.722772  97.277228
 2020       0.000000  4.285714  95.714286
 2021       0.000000  3.092784  96.907216
 2022       0.000000  3.080569  96.919431
 2023       0.000000  4.129794  95.870206,
 'AUG Concl': AUG Concl         I         R          S
 Data Year
 2003       0.781250  0.000000  99.218750
 2004       1.476015  0.000000  98.523985
 2005       1.041667  0.781250  98.177083
 2006       0.485437  0.485437  99.029126
 2007       0.000000  0.519481  99.480519
 2008       0.452489  0.000000  99.547511
 2009       0.243902  0.000000  99.756098
 2010       0.194932  0.389864  99.415205
 2011       0.000000  0.255754  99.744246
 2012       0.274725  0.549451  99.175824
 2013       0.785340  0.000000  99.214660
 2014       0.684932  0.456621  98.858447
 2015       0.424628  0.849257  98.726115
 2016       0.228833  0.915332  98.855835
 2017       0.232019  0.464037  99.303944
 2018       0.226757  0.226757  99.546485
 2019       0.247525  0.000000  99.752475
 2020       1.071429  0.714286  98.214286
 2021       0.687285  0.343643  98.969072
 2022       0.236967  0.236967  99.526066
 2023       0.589971  0.000000  99.410029,
 'AXO Concl': AXO Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  0.260417   99.739583
 2006       0.000000  0.485437   99.514563
 2007       0.000000  0.259740   99.740260
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.000000  0.000000  100.000000
 2011       0.000000  0.255754   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.000000  0.261780   99.738220
 2014       0.000000  0.456621   99.543379
 2015       0.000000  0.212314   99.787686
 2016       0.228833  0.686499   99.084668
 2017       0.000000  0.464037   99.535963
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.247525   99.752475
 2020       0.000000  0.714286   99.285714
 2021       0.000000  0.000000  100.000000
 2022       0.000000  0.236967   99.763033
 2023       0.000000  0.000000  100.000000,
 'CHL Concl': CHL Concl         I         R           S
 Data Year
 2003       0.390625  0.390625   99.218750
 2004       0.369004  0.369004   99.261993
 2005       0.000000  0.520833   99.479167
 2006       0.000000  0.000000  100.000000
 2007       0.779221  0.519481   98.701299
 2008       0.226244  0.452489   99.321267
 2009       0.243902  0.000000   99.756098
 2010       0.389864  0.584795   99.025341
 2011       0.255754  0.000000   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.785340  0.261780   98.952880
 2014       0.456621  1.141553   98.401826
 2015       0.636943  0.212314   99.150743
 2016       0.228833  1.601831   98.169336
 2017       1.392111  1.392111   97.215777
 2018       0.680272  0.453515   98.866213
 2019       0.742574  0.495050   98.762376
 2020       0.357143  1.071429   98.571429
 2021       0.343643  1.030928   98.625430
 2022       0.710900  0.000000   99.289100
 2023       1.474926  0.000000   98.525074,
 'CIP Concl': CIP Concl          I         R          S
 Data Year
 2003        3.906250  0.000000  96.093750
 2004        6.273063  0.369004  93.357934
 2005        3.906250  0.000000  96.093750
 2006        7.038835  0.000000  92.961165
 2007        5.974026  0.000000  94.025974
 2008        7.239819  0.000000  92.760181
 2009        3.658537  0.000000  96.341463
 2010        4.873294  0.194932  94.931774
 2011        7.161125  0.000000  92.838875
 2012        7.967033  0.000000  92.032967
 2013        5.497382  0.000000  94.502618
 2014        7.762557  0.228311  92.009132
 2015       13.800425  0.000000  86.199575
 2016       11.670481  0.000000  88.329519
 2017       20.649652  0.000000  79.350348
 2018       22.222222  0.226757  77.551020
 2019       29.207921  0.000000  70.792079
 2020       28.928571  0.000000  71.071429
 2021       31.615120  0.343643  68.041237
 2022       37.677725  0.236967  62.085308
 2023       48.377581  0.000000  51.622419,
 'COT Concl': COT Concl         R           S
 Data Year
 2003       0.781250   99.218750
 2004       0.000000  100.000000
 2005       0.520833   99.479167
 2006       0.485437   99.514563
 2007       1.038961   98.961039
 2008       0.904977   99.095023
 2009       0.731707   99.268293
 2010       0.974659   99.025341
 2011       0.511509   99.488491
 2012       1.098901   98.901099
 2013       0.523560   99.476440
 2014       0.456621   99.543379
 2015       1.910828   98.089172
 2016       1.144165   98.855835
 2017       0.928074   99.071926
 2018       0.226757   99.773243
 2019       0.247525   99.752475
 2020       0.000000  100.000000
 2021       0.343643   99.656357
 2022       0.236967   99.763033
 2023       0.000000  100.000000,
 'FIS Concl': FIS Concl         R          S      X
 Data Year
 2003       0.000000   0.000000  100.0
 2004       1.845018  98.154982    0.0
 2005       1.562500  98.437500    0.0
 2006       1.456311  98.543689    0.0
 2007       1.558442  98.441558    0.0
 2008       1.357466  98.642534    0.0
 2009       1.707317  98.292683    0.0
 2010       1.949318  98.050682    0.0
 2011       2.046036  97.953964    0.0
 2012       2.747253  97.252747    0.0
 2013       1.570681  98.429319    0.0
 2014       1.826484  98.173516    0.0
 2015       3.397028  96.602972    0.0
 2016       4.118993  95.881007    0.0
 2017       2.784223  97.215777    0.0
 2018       1.587302  98.412698    0.0
 2019       1.485149  98.514851    0.0
 2020       2.142857  97.857143    0.0
 2021       2.061856  97.938144    0.0
 2022       2.132701  97.867299    0.0
 2023       2.064897  97.935103    0.0,
 'FOX Concl': FOX Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  1.041667   98.958333
 2006       0.000000  0.485437   99.514563
 2007       0.259740  0.259740   99.480519
 2008       0.452489  0.000000   99.547511
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.000000   99.805068
 2011       0.511509  0.255754   99.232737
 2012       0.549451  0.549451   98.901099
 2013       0.261780  0.000000   99.738220
 2014       0.000000  0.684932   99.315068
 2015       0.636943  0.424628   98.938429
 2016       0.228833  0.686499   99.084668
 2017       0.232019  0.696056   99.071926
 2018       0.000000  0.226757   99.773243
 2019       0.495050  0.000000   99.504950
 2020       0.357143  0.714286   98.928571
 2021       1.030928  0.343643   98.625430
 2022       0.000000  0.236967   99.763033
 2023       0.294985  0.000000   99.705015,
 'GEN Concl': GEN Concl         I         R           S
 Data Year
 2003       0.000000  0.390625   99.609375
 2004       0.000000  0.369004   99.630996
 2005       0.000000  0.781250   99.218750
 2006       0.000000  0.242718   99.757282
 2007       0.000000  0.000000  100.000000
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.194932   99.610136
 2011       0.000000  0.511509   99.488491
 2012       0.000000  0.000000  100.000000
 2013       0.000000  0.000000  100.000000
 2014       0.456621  0.000000   99.543379
 2015       0.000000  0.424628   99.575372
 2016       0.000000  0.000000  100.000000
 2017       0.000000  0.000000  100.000000
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.000000  100.000000
 2020       0.000000  0.000000  100.000000
 2021       0.000000  0.343643   99.656357
 2022       0.000000  0.000000  100.000000
 2023       0.000000  0.000000  100.000000,
 'NAL Concl': NAL Concl          R          S
 Data Year
 2003        4.687500  95.312500
 2004        6.642066  93.357934
 2005        4.687500  95.312500
 2006        7.038835  92.961165
 2007        5.714286  94.285714
 2008        7.239819  92.760181
 2009        3.658537  96.341463
 2010        5.263158  94.736842
 2011        7.161125  92.838875
 2012        7.692308  92.307692
 2013        5.759162  94.240838
 2014        7.990868  92.009132
 2015       13.163482  86.836518
 2016       11.670481  88.329519
 2017       20.417633  79.582367
 2018       21.315193  78.684807
 2019       28.960396  71.039604
 2020       28.571429  71.428571
 2021       31.615120  68.384880
 2022       36.966825  63.033175
 2023       47.492625  52.507375,
 'STR Concl': STR Concl         R          S           X
 Data Year
 2003       1.171875  98.828125    0.000000
 2004       2.214022  97.785978    0.000000
 2005       1.041667  98.958333    0.000000
 2006       1.213592  98.786408    0.000000
 2007       0.519481  99.480519    0.000000
 2008       0.678733  99.321267    0.000000
 2009       1.219512  98.780488    0.000000
 2010       0.584795  99.415205    0.000000
 2011       1.790281  98.209719    0.000000
 2012       1.923077  98.076923    0.000000
 2013       2.617801  97.382199    0.000000
 2014       2.968037  97.031963    0.000000
 2015       5.732484  94.267516    0.000000
 2016       4.347826  95.423341    0.228833
 2017       3.016241  96.983759    0.000000
 2018       1.587302  98.412698    0.000000
 2019       1.980198  97.772277    0.247525
 2020       0.000000   0.000000  100.000000
 2021       0.000000   0.000000  100.000000
 2022       0.000000   0.000000  100.000000
 2023       0.000000   0.000000  100.000000,
 'TET Concl': TET Concl         I         R          S
 Data Year
 2003       0.000000  1.562500  98.437500
 2004       1.107011  3.321033  95.571956
 2005       0.000000  2.343750  97.656250
 2006       0.242718  1.699029  98.058252
 2007       0.259740  3.896104  95.844156
 2008       0.226244  1.809955  97.963801
 2009       0.243902  1.219512  98.536585
 2010       0.000000  2.144250  97.855750
 2011       0.767263  1.790281  97.442455
 2012       0.549451  3.571429  95.879121
 2013       0.523560  4.450262  95.026178
 2014       0.684932  2.511416  96.803653
 2015       2.123142  4.670913  93.205945
 2016       1.372998  7.093822  91.533181
 2017       0.928074  4.640371  94.431555
 2018       0.000000  5.895692  94.104308
 2019       0.000000  4.702970  95.297030
 2020       0.714286  3.214286  96.071429
 2021       0.343643  3.436426  96.219931
 2022       0.000000  1.421801  98.578199
 2023       1.179941  1.474926  97.345133}

In [22]:
# Count the occurrences of X in the FIS Concl column for the year 2003
x_count_2003 = salmonella_isolate_df_cleaned.loc[
    (salmonella_isolate_df_cleaned['Data Year'] == 2003), 
    'FIS Concl'
].value_counts().get('X', 0)

# Calculate the average percentages for R and S from 2004-2009
average_r = (1.845018 + 1.562500 + 1.456311 + 1.558442 + 1.357466 + 1.707317) / 6
average_s = (98.154982 + 98.437500 + 98.543689 + 98.441558 + 98.642534 + 98.292683) / 6

# Create a function to assign values based on the calculated percentages
def assign_values_for_2003(count):
    # Ensure count is an integer
    count = int(count)  # Convert to integer
    r_count = int(count * (average_r / (average_r + average_s)))  # proportion of R
    s_count = count - r_count  # rest will be S
    
    # Create the list to assign
    return ['R'] * r_count + ['S'] * s_count

# Assign values for 2003
x_values_2003 = assign_values_for_2003(x_count_2003)

# Randomly shuffle the assigned values
np.random.shuffle(x_values_2003)

# Update the DataFrame
salmonella_isolate_df_cleaned.loc[salmonella_isolate_df_cleaned['Data Year'] == 2003, 'FIS Concl'] = x_values_2003

In [23]:
# Display the calculated yearly percentages for each conclusion column
yearly_percentages = {}

# Loop through each conclusion column to calculate yearly percentages
for col in concl_columns:
    # Calculate the total counts for each category per year
    total_counts = salmonella_isolate_df_cleaned.groupby('Data Year')[col].value_counts(normalize=True).unstack(fill_value=0) * 100
    
    # Store the percentages in the dictionary
    yearly_percentages[col] = total_counts

# Display the calculated yearly percentages for each conclusion column
yearly_percentages_outputs = {col: data for col, data in yearly_percentages.items()}
yearly_percentages_outputs

{'AMP Concl': AMP Concl         I         R          S
 Data Year
 2003       0.000000  2.343750  97.656250
 2004       0.000000  4.059041  95.940959
 2005       0.000000  2.604167  97.395833
 2006       0.000000  4.126214  95.873786
 2007       0.000000  2.077922  97.922078
 2008       0.226244  4.072398  95.701357
 2009       0.000000  3.902439  96.097561
 2010       0.000000  2.339181  97.660819
 2011       0.000000  5.115090  94.884910
 2012       0.000000  4.120879  95.879121
 2013       0.000000  5.759162  94.240838
 2014       0.000000  3.196347  96.803653
 2015       0.000000  5.944798  94.055202
 2016       0.228833  5.263158  94.508009
 2017       0.000000  3.248260  96.751740
 2018       0.000000  1.814059  98.185941
 2019       0.000000  2.722772  97.277228
 2020       0.000000  4.285714  95.714286
 2021       0.000000  3.092784  96.907216
 2022       0.000000  3.080569  96.919431
 2023       0.000000  4.129794  95.870206,
 'AUG Concl': AUG Concl         I         R          S
 Data Year
 2003       0.781250  0.000000  99.218750
 2004       1.476015  0.000000  98.523985
 2005       1.041667  0.781250  98.177083
 2006       0.485437  0.485437  99.029126
 2007       0.000000  0.519481  99.480519
 2008       0.452489  0.000000  99.547511
 2009       0.243902  0.000000  99.756098
 2010       0.194932  0.389864  99.415205
 2011       0.000000  0.255754  99.744246
 2012       0.274725  0.549451  99.175824
 2013       0.785340  0.000000  99.214660
 2014       0.684932  0.456621  98.858447
 2015       0.424628  0.849257  98.726115
 2016       0.228833  0.915332  98.855835
 2017       0.232019  0.464037  99.303944
 2018       0.226757  0.226757  99.546485
 2019       0.247525  0.000000  99.752475
 2020       1.071429  0.714286  98.214286
 2021       0.687285  0.343643  98.969072
 2022       0.236967  0.236967  99.526066
 2023       0.589971  0.000000  99.410029,
 'AXO Concl': AXO Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  0.260417   99.739583
 2006       0.000000  0.485437   99.514563
 2007       0.000000  0.259740   99.740260
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.000000  0.000000  100.000000
 2011       0.000000  0.255754   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.000000  0.261780   99.738220
 2014       0.000000  0.456621   99.543379
 2015       0.000000  0.212314   99.787686
 2016       0.228833  0.686499   99.084668
 2017       0.000000  0.464037   99.535963
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.247525   99.752475
 2020       0.000000  0.714286   99.285714
 2021       0.000000  0.000000  100.000000
 2022       0.000000  0.236967   99.763033
 2023       0.000000  0.000000  100.000000,
 'CHL Concl': CHL Concl         I         R           S
 Data Year
 2003       0.390625  0.390625   99.218750
 2004       0.369004  0.369004   99.261993
 2005       0.000000  0.520833   99.479167
 2006       0.000000  0.000000  100.000000
 2007       0.779221  0.519481   98.701299
 2008       0.226244  0.452489   99.321267
 2009       0.243902  0.000000   99.756098
 2010       0.389864  0.584795   99.025341
 2011       0.255754  0.000000   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.785340  0.261780   98.952880
 2014       0.456621  1.141553   98.401826
 2015       0.636943  0.212314   99.150743
 2016       0.228833  1.601831   98.169336
 2017       1.392111  1.392111   97.215777
 2018       0.680272  0.453515   98.866213
 2019       0.742574  0.495050   98.762376
 2020       0.357143  1.071429   98.571429
 2021       0.343643  1.030928   98.625430
 2022       0.710900  0.000000   99.289100
 2023       1.474926  0.000000   98.525074,
 'CIP Concl': CIP Concl          I         R          S
 Data Year
 2003        3.906250  0.000000  96.093750
 2004        6.273063  0.369004  93.357934
 2005        3.906250  0.000000  96.093750
 2006        7.038835  0.000000  92.961165
 2007        5.974026  0.000000  94.025974
 2008        7.239819  0.000000  92.760181
 2009        3.658537  0.000000  96.341463
 2010        4.873294  0.194932  94.931774
 2011        7.161125  0.000000  92.838875
 2012        7.967033  0.000000  92.032967
 2013        5.497382  0.000000  94.502618
 2014        7.762557  0.228311  92.009132
 2015       13.800425  0.000000  86.199575
 2016       11.670481  0.000000  88.329519
 2017       20.649652  0.000000  79.350348
 2018       22.222222  0.226757  77.551020
 2019       29.207921  0.000000  70.792079
 2020       28.928571  0.000000  71.071429
 2021       31.615120  0.343643  68.041237
 2022       37.677725  0.236967  62.085308
 2023       48.377581  0.000000  51.622419,
 'COT Concl': COT Concl         R           S
 Data Year
 2003       0.781250   99.218750
 2004       0.000000  100.000000
 2005       0.520833   99.479167
 2006       0.485437   99.514563
 2007       1.038961   98.961039
 2008       0.904977   99.095023
 2009       0.731707   99.268293
 2010       0.974659   99.025341
 2011       0.511509   99.488491
 2012       1.098901   98.901099
 2013       0.523560   99.476440
 2014       0.456621   99.543379
 2015       1.910828   98.089172
 2016       1.144165   98.855835
 2017       0.928074   99.071926
 2018       0.226757   99.773243
 2019       0.247525   99.752475
 2020       0.000000  100.000000
 2021       0.343643   99.656357
 2022       0.236967   99.763033
 2023       0.000000  100.000000,
 'FIS Concl': FIS Concl         R          S
 Data Year
 2003       1.562500  98.437500
 2004       1.845018  98.154982
 2005       1.562500  98.437500
 2006       1.456311  98.543689
 2007       1.558442  98.441558
 2008       1.357466  98.642534
 2009       1.707317  98.292683
 2010       1.949318  98.050682
 2011       2.046036  97.953964
 2012       2.747253  97.252747
 2013       1.570681  98.429319
 2014       1.826484  98.173516
 2015       3.397028  96.602972
 2016       4.118993  95.881007
 2017       2.784223  97.215777
 2018       1.587302  98.412698
 2019       1.485149  98.514851
 2020       2.142857  97.857143
 2021       2.061856  97.938144
 2022       2.132701  97.867299
 2023       2.064897  97.935103,
 'FOX Concl': FOX Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  1.041667   98.958333
 2006       0.000000  0.485437   99.514563
 2007       0.259740  0.259740   99.480519
 2008       0.452489  0.000000   99.547511
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.000000   99.805068
 2011       0.511509  0.255754   99.232737
 2012       0.549451  0.549451   98.901099
 2013       0.261780  0.000000   99.738220
 2014       0.000000  0.684932   99.315068
 2015       0.636943  0.424628   98.938429
 2016       0.228833  0.686499   99.084668
 2017       0.232019  0.696056   99.071926
 2018       0.000000  0.226757   99.773243
 2019       0.495050  0.000000   99.504950
 2020       0.357143  0.714286   98.928571
 2021       1.030928  0.343643   98.625430
 2022       0.000000  0.236967   99.763033
 2023       0.294985  0.000000   99.705015,
 'GEN Concl': GEN Concl         I         R           S
 Data Year
 2003       0.000000  0.390625   99.609375
 2004       0.000000  0.369004   99.630996
 2005       0.000000  0.781250   99.218750
 2006       0.000000  0.242718   99.757282
 2007       0.000000  0.000000  100.000000
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.194932   99.610136
 2011       0.000000  0.511509   99.488491
 2012       0.000000  0.000000  100.000000
 2013       0.000000  0.000000  100.000000
 2014       0.456621  0.000000   99.543379
 2015       0.000000  0.424628   99.575372
 2016       0.000000  0.000000  100.000000
 2017       0.000000  0.000000  100.000000
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.000000  100.000000
 2020       0.000000  0.000000  100.000000
 2021       0.000000  0.343643   99.656357
 2022       0.000000  0.000000  100.000000
 2023       0.000000  0.000000  100.000000,
 'NAL Concl': NAL Concl          R          S
 Data Year
 2003        4.687500  95.312500
 2004        6.642066  93.357934
 2005        4.687500  95.312500
 2006        7.038835  92.961165
 2007        5.714286  94.285714
 2008        7.239819  92.760181
 2009        3.658537  96.341463
 2010        5.263158  94.736842
 2011        7.161125  92.838875
 2012        7.692308  92.307692
 2013        5.759162  94.240838
 2014        7.990868  92.009132
 2015       13.163482  86.836518
 2016       11.670481  88.329519
 2017       20.417633  79.582367
 2018       21.315193  78.684807
 2019       28.960396  71.039604
 2020       28.571429  71.428571
 2021       31.615120  68.384880
 2022       36.966825  63.033175
 2023       47.492625  52.507375,
 'STR Concl': STR Concl         R          S           X
 Data Year
 2003       1.171875  98.828125    0.000000
 2004       2.214022  97.785978    0.000000
 2005       1.041667  98.958333    0.000000
 2006       1.213592  98.786408    0.000000
 2007       0.519481  99.480519    0.000000
 2008       0.678733  99.321267    0.000000
 2009       1.219512  98.780488    0.000000
 2010       0.584795  99.415205    0.000000
 2011       1.790281  98.209719    0.000000
 2012       1.923077  98.076923    0.000000
 2013       2.617801  97.382199    0.000000
 2014       2.968037  97.031963    0.000000
 2015       5.732484  94.267516    0.000000
 2016       4.347826  95.423341    0.228833
 2017       3.016241  96.983759    0.000000
 2018       1.587302  98.412698    0.000000
 2019       1.980198  97.772277    0.247525
 2020       0.000000   0.000000  100.000000
 2021       0.000000   0.000000  100.000000
 2022       0.000000   0.000000  100.000000
 2023       0.000000   0.000000  100.000000,
 'TET Concl': TET Concl         I         R          S
 Data Year
 2003       0.000000  1.562500  98.437500
 2004       1.107011  3.321033  95.571956
 2005       0.000000  2.343750  97.656250
 2006       0.242718  1.699029  98.058252
 2007       0.259740  3.896104  95.844156
 2008       0.226244  1.809955  97.963801
 2009       0.243902  1.219512  98.536585
 2010       0.000000  2.144250  97.855750
 2011       0.767263  1.790281  97.442455
 2012       0.549451  3.571429  95.879121
 2013       0.523560  4.450262  95.026178
 2014       0.684932  2.511416  96.803653
 2015       2.123142  4.670913  93.205945
 2016       1.372998  7.093822  91.533181
 2017       0.928074  4.640371  94.431555
 2018       0.000000  5.895692  94.104308
 2019       0.000000  4.702970  95.297030
 2020       0.714286  3.214286  96.071429
 2021       0.343643  3.436426  96.219931
 2022       0.000000  1.421801  98.578199
 2023       1.179941  1.474926  97.345133}

In [24]:
# Initialize a dictionary to hold yearly percentages for STR Concl
yearly_percentages_str = {}

# Loop through each year to calculate percentages
for year in range(2003, 2024):
    # Filter the data for the specific year
    yearly_data = salmonella_isolate_df_cleaned[salmonella_isolate_df_cleaned['Data Year'] == year]
    
    # Count occurrences of each value in STR Concl
    counts = yearly_data['STR Concl'].value_counts(normalize=True) * 100  # Get percentages
    
    # Store the percentages in the dictionary
    yearly_percentages_str[year] = counts

# Display the calculated yearly percentages for STR Concl
yearly_percentages_str

{2003: STR Concl
 S    98.828125
 R     1.171875
 Name: proportion, dtype: float64,
 2004: STR Concl
 S    97.785978
 R     2.214022
 Name: proportion, dtype: float64,
 2005: STR Concl
 S    98.958333
 R     1.041667
 Name: proportion, dtype: float64,
 2006: STR Concl
 S    98.786408
 R     1.213592
 Name: proportion, dtype: float64,
 2007: STR Concl
 S    99.480519
 R     0.519481
 Name: proportion, dtype: float64,
 2008: STR Concl
 S    99.321267
 R     0.678733
 Name: proportion, dtype: float64,
 2009: STR Concl
 S    98.780488
 R     1.219512
 Name: proportion, dtype: float64,
 2010: STR Concl
 S    99.415205
 R     0.584795
 Name: proportion, dtype: float64,
 2011: STR Concl
 S    98.209719
 R     1.790281
 Name: proportion, dtype: float64,
 2012: STR Concl
 S    98.076923
 R     1.923077
 Name: proportion, dtype: float64,
 2013: STR Concl
 S    97.382199
 R     2.617801
 Name: proportion, dtype: float64,
 2014: STR Concl
 S    97.031963
 R     2.968037
 Name: proportion, dtype: float64,
 2015: STR Concl
 S    94.267516
 R     5.732484
 Name: proportion, dtype: float64,
 2016: STR Concl
 S    95.423341
 R     4.347826
 X     0.228833
 Name: proportion, dtype: float64,
 2017: STR Concl
 S    96.983759
 R     3.016241
 Name: proportion, dtype: float64,
 2018: STR Concl
 S    98.412698
 R     1.587302
 Name: proportion, dtype: float64,
 2019: STR Concl
 S    97.772277
 R     1.980198
 X     0.247525
 Name: proportion, dtype: float64,
 2020: STR Concl
 X    100.0
 Name: proportion, dtype: float64,
 2021: STR Concl
 X    100.0
 Name: proportion, dtype: float64,
 2022: STR Concl
 X    100.0
 Name: proportion, dtype: float64,
 2023: STR Concl
 X    100.0
 Name: proportion, dtype: float64}

In [25]:
# Calculate historical averages for R and S from 2003 to 2019
average_r = sum([yearly_percentages_str[year].get('R', 0) for year in range(2003, 2020)]) / (2020 - 2003)
average_s = sum([yearly_percentages_str[year].get('S', 0) for year in range(2003, 2020)]) / (2020 - 2003)

# Impute missing values for STR Concl from 2020 to 2023
for year in range(2020, 2024):
    # Count total records for the year
    total_counts = salmonella_isolate_df_cleaned[salmonella_isolate_df_cleaned['Data Year'] == year].shape[0]

    # Calculate number of R and S based on the average proportions
    r_count = int(total_counts * (average_r / (average_r + average_s)))
    s_count = total_counts - r_count  # R + S should equal total_counts

    # Update the DataFrame
    salmonella_isolate_df_cleaned.loc[salmonella_isolate_df_cleaned['Data Year'] == year, 'STR Concl'] = 'R'
    salmonella_isolate_df_cleaned.loc[salmonella_isolate_df_cleaned['Data Year'] == year, 'STR Concl'] = 'S'

In [26]:
# Initialize a dictionary to store counts of 'X' values
x_values_count = {}

# Identify all conclusion columns
conclusion_columns = [col for col in salmonella_isolate_df_cleaned.columns if 'Concl' in col]

# Count 'X' values in each conclusion column
for col in conclusion_columns:
    x_count = salmonella_isolate_df_cleaned[col].value_counts().get('X', 0)
    x_values_count[col] = x_count

print(x_values_count)

{'AMP Concl': 0, 'AUG Concl': 0, 'AXO Concl': 0, 'CHL Concl': 0, 'CIP Concl': 0, 'COT Concl': 0, 'FIS Concl': 0, 'FOX Concl': 0, 'GEN Concl': 0, 'NAL Concl': 0, 'STR Concl': 2, 'TET Concl': 0}

In [27]:
# Display the calculated yearly percentages for each conclusion column
yearly_percentages = {}

# Loop through each conclusion column to calculate yearly percentages
for col in concl_columns:
    # Calculate the total counts for each category per year
    total_counts = salmonella_isolate_df_cleaned.groupby('Data Year')[col].value_counts(normalize=True).unstack(fill_value=0) * 100
    
    # Store the percentages in the dictionary
    yearly_percentages[col] = total_counts

# Display the calculated yearly percentages for each conclusion column
yearly_percentages_outputs = {col: data for col, data in yearly_percentages.items()}
yearly_percentages_outputs

{'AMP Concl': AMP Concl         I         R          S
 Data Year
 2003       0.000000  2.343750  97.656250
 2004       0.000000  4.059041  95.940959
 2005       0.000000  2.604167  97.395833
 2006       0.000000  4.126214  95.873786
 2007       0.000000  2.077922  97.922078
 2008       0.226244  4.072398  95.701357
 2009       0.000000  3.902439  96.097561
 2010       0.000000  2.339181  97.660819
 2011       0.000000  5.115090  94.884910
 2012       0.000000  4.120879  95.879121
 2013       0.000000  5.759162  94.240838
 2014       0.000000  3.196347  96.803653
 2015       0.000000  5.944798  94.055202
 2016       0.228833  5.263158  94.508009
 2017       0.000000  3.248260  96.751740
 2018       0.000000  1.814059  98.185941
 2019       0.000000  2.722772  97.277228
 2020       0.000000  4.285714  95.714286
 2021       0.000000  3.092784  96.907216
 2022       0.000000  3.080569  96.919431
 2023       0.000000  4.129794  95.870206,
 'AUG Concl': AUG Concl         I         R          S
 Data Year
 2003       0.781250  0.000000  99.218750
 2004       1.476015  0.000000  98.523985
 2005       1.041667  0.781250  98.177083
 2006       0.485437  0.485437  99.029126
 2007       0.000000  0.519481  99.480519
 2008       0.452489  0.000000  99.547511
 2009       0.243902  0.000000  99.756098
 2010       0.194932  0.389864  99.415205
 2011       0.000000  0.255754  99.744246
 2012       0.274725  0.549451  99.175824
 2013       0.785340  0.000000  99.214660
 2014       0.684932  0.456621  98.858447
 2015       0.424628  0.849257  98.726115
 2016       0.228833  0.915332  98.855835
 2017       0.232019  0.464037  99.303944
 2018       0.226757  0.226757  99.546485
 2019       0.247525  0.000000  99.752475
 2020       1.071429  0.714286  98.214286
 2021       0.687285  0.343643  98.969072
 2022       0.236967  0.236967  99.526066
 2023       0.589971  0.000000  99.410029,
 'AXO Concl': AXO Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  0.260417   99.739583
 2006       0.000000  0.485437   99.514563
 2007       0.000000  0.259740   99.740260
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.000000  0.000000  100.000000
 2011       0.000000  0.255754   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.000000  0.261780   99.738220
 2014       0.000000  0.456621   99.543379
 2015       0.000000  0.212314   99.787686
 2016       0.228833  0.686499   99.084668
 2017       0.000000  0.464037   99.535963
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.247525   99.752475
 2020       0.000000  0.714286   99.285714
 2021       0.000000  0.000000  100.000000
 2022       0.000000  0.236967   99.763033
 2023       0.000000  0.000000  100.000000,
 'CHL Concl': CHL Concl         I         R           S
 Data Year
 2003       0.390625  0.390625   99.218750
 2004       0.369004  0.369004   99.261993
 2005       0.000000  0.520833   99.479167
 2006       0.000000  0.000000  100.000000
 2007       0.779221  0.519481   98.701299
 2008       0.226244  0.452489   99.321267
 2009       0.243902  0.000000   99.756098
 2010       0.389864  0.584795   99.025341
 2011       0.255754  0.000000   99.744246
 2012       0.000000  0.549451   99.450549
 2013       0.785340  0.261780   98.952880
 2014       0.456621  1.141553   98.401826
 2015       0.636943  0.212314   99.150743
 2016       0.228833  1.601831   98.169336
 2017       1.392111  1.392111   97.215777
 2018       0.680272  0.453515   98.866213
 2019       0.742574  0.495050   98.762376
 2020       0.357143  1.071429   98.571429
 2021       0.343643  1.030928   98.625430
 2022       0.710900  0.000000   99.289100
 2023       1.474926  0.000000   98.525074,
 'CIP Concl': CIP Concl          I         R          S
 Data Year
 2003        3.906250  0.000000  96.093750
 2004        6.273063  0.369004  93.357934
 2005        3.906250  0.000000  96.093750
 2006        7.038835  0.000000  92.961165
 2007        5.974026  0.000000  94.025974
 2008        7.239819  0.000000  92.760181
 2009        3.658537  0.000000  96.341463
 2010        4.873294  0.194932  94.931774
 2011        7.161125  0.000000  92.838875
 2012        7.967033  0.000000  92.032967
 2013        5.497382  0.000000  94.502618
 2014        7.762557  0.228311  92.009132
 2015       13.800425  0.000000  86.199575
 2016       11.670481  0.000000  88.329519
 2017       20.649652  0.000000  79.350348
 2018       22.222222  0.226757  77.551020
 2019       29.207921  0.000000  70.792079
 2020       28.928571  0.000000  71.071429
 2021       31.615120  0.343643  68.041237
 2022       37.677725  0.236967  62.085308
 2023       48.377581  0.000000  51.622419,
 'COT Concl': COT Concl         R           S
 Data Year
 2003       0.781250   99.218750
 2004       0.000000  100.000000
 2005       0.520833   99.479167
 2006       0.485437   99.514563
 2007       1.038961   98.961039
 2008       0.904977   99.095023
 2009       0.731707   99.268293
 2010       0.974659   99.025341
 2011       0.511509   99.488491
 2012       1.098901   98.901099
 2013       0.523560   99.476440
 2014       0.456621   99.543379
 2015       1.910828   98.089172
 2016       1.144165   98.855835
 2017       0.928074   99.071926
 2018       0.226757   99.773243
 2019       0.247525   99.752475
 2020       0.000000  100.000000
 2021       0.343643   99.656357
 2022       0.236967   99.763033
 2023       0.000000  100.000000,
 'FIS Concl': FIS Concl         R          S
 Data Year
 2003       1.562500  98.437500
 2004       1.845018  98.154982
 2005       1.562500  98.437500
 2006       1.456311  98.543689
 2007       1.558442  98.441558
 2008       1.357466  98.642534
 2009       1.707317  98.292683
 2010       1.949318  98.050682
 2011       2.046036  97.953964
 2012       2.747253  97.252747
 2013       1.570681  98.429319
 2014       1.826484  98.173516
 2015       3.397028  96.602972
 2016       4.118993  95.881007
 2017       2.784223  97.215777
 2018       1.587302  98.412698
 2019       1.485149  98.514851
 2020       2.142857  97.857143
 2021       2.061856  97.938144
 2022       2.132701  97.867299
 2023       2.064897  97.935103,
 'FOX Concl': FOX Concl         I         R           S
 Data Year
 2003       0.000000  0.000000  100.000000
 2004       0.000000  0.000000  100.000000
 2005       0.000000  1.041667   98.958333
 2006       0.000000  0.485437   99.514563
 2007       0.259740  0.259740   99.480519
 2008       0.452489  0.000000   99.547511
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.000000   99.805068
 2011       0.511509  0.255754   99.232737
 2012       0.549451  0.549451   98.901099
 2013       0.261780  0.000000   99.738220
 2014       0.000000  0.684932   99.315068
 2015       0.636943  0.424628   98.938429
 2016       0.228833  0.686499   99.084668
 2017       0.232019  0.696056   99.071926
 2018       0.000000  0.226757   99.773243
 2019       0.495050  0.000000   99.504950
 2020       0.357143  0.714286   98.928571
 2021       1.030928  0.343643   98.625430
 2022       0.000000  0.236967   99.763033
 2023       0.294985  0.000000   99.705015,
 'GEN Concl': GEN Concl         I         R           S
 Data Year
 2003       0.000000  0.390625   99.609375
 2004       0.000000  0.369004   99.630996
 2005       0.000000  0.781250   99.218750
 2006       0.000000  0.242718   99.757282
 2007       0.000000  0.000000  100.000000
 2008       0.000000  0.226244   99.773756
 2009       0.000000  0.000000  100.000000
 2010       0.194932  0.194932   99.610136
 2011       0.000000  0.511509   99.488491
 2012       0.000000  0.000000  100.000000
 2013       0.000000  0.000000  100.000000
 2014       0.456621  0.000000   99.543379
 2015       0.000000  0.424628   99.575372
 2016       0.000000  0.000000  100.000000
 2017       0.000000  0.000000  100.000000
 2018       0.000000  0.226757   99.773243
 2019       0.000000  0.000000  100.000000
 2020       0.000000  0.000000  100.000000
 2021       0.000000  0.343643   99.656357
 2022       0.000000  0.000000  100.000000
 2023       0.000000  0.000000  100.000000,
 'NAL Concl': NAL Concl          R          S
 Data Year
 2003        4.687500  95.312500
 2004        6.642066  93.357934
 2005        4.687500  95.312500
 2006        7.038835  92.961165
 2007        5.714286  94.285714
 2008        7.239819  92.760181
 2009        3.658537  96.341463
 2010        5.263158  94.736842
 2011        7.161125  92.838875
 2012        7.692308  92.307692
 2013        5.759162  94.240838
 2014        7.990868  92.009132
 2015       13.163482  86.836518
 2016       11.670481  88.329519
 2017       20.417633  79.582367
 2018       21.315193  78.684807
 2019       28.960396  71.039604
 2020       28.571429  71.428571
 2021       31.615120  68.384880
 2022       36.966825  63.033175
 2023       47.492625  52.507375,
 'STR Concl': STR Concl         R           S         X
 Data Year
 2003       1.171875   98.828125  0.000000
 2004       2.214022   97.785978  0.000000
 2005       1.041667   98.958333  0.000000
 2006       1.213592   98.786408  0.000000
 2007       0.519481   99.480519  0.000000
 2008       0.678733   99.321267  0.000000
 2009       1.219512   98.780488  0.000000
 2010       0.584795   99.415205  0.000000
 2011       1.790281   98.209719  0.000000
 2012       1.923077   98.076923  0.000000
 2013       2.617801   97.382199  0.000000
 2014       2.968037   97.031963  0.000000
 2015       5.732484   94.267516  0.000000
 2016       4.347826   95.423341  0.228833
 2017       3.016241   96.983759  0.000000
 2018       1.587302   98.412698  0.000000
 2019       1.980198   97.772277  0.247525
 2020       0.000000  100.000000  0.000000
 2021       0.000000  100.000000  0.000000
 2022       0.000000  100.000000  0.000000
 2023       0.000000  100.000000  0.000000,
 'TET Concl': TET Concl         I         R          S
 Data Year
 2003       0.000000  1.562500  98.437500
 2004       1.107011  3.321033  95.571956
 2005       0.000000  2.343750  97.656250
 2006       0.242718  1.699029  98.058252
 2007       0.259740  3.896104  95.844156
 2008       0.226244  1.809955  97.963801
 2009       0.243902  1.219512  98.536585
 2010       0.000000  2.144250  97.855750
 2011       0.767263  1.790281  97.442455
 2012       0.549451  3.571429  95.879121
 2013       0.523560  4.450262  95.026178
 2014       0.684932  2.511416  96.803653
 2015       2.123142  4.670913  93.205945
 2016       1.372998  7.093822  91.533181
 2017       0.928074  4.640371  94.431555
 2018       0.000000  5.895692  94.104308
 2019       0.000000  4.702970  95.297030
 2020       0.714286  3.214286  96.071429
 2021       0.343643  3.436426  96.219931
 2022       0.000000  1.421801  98.578199
 2023       1.179941  1.474926  97.345133}

In [28]:
# Check for any remaining 'X' values
remaining_x_count = (salmonella_isolate_df_cleaned['STR Concl'] == 'X').sum()
print(f"Remaining 'X' values in STR Concl: {remaining_x_count}")

Remaining 'X' values in STR Concl: 2

In [29]:
# Drop rows with 'X' values in the STR Concl column
salmonella_isolate_df_cleaned = salmonella_isolate_df_cleaned[salmonella_isolate_df_cleaned['STR Concl'] != 'X']

# Check the shape of the DataFrame after dropping
updated_shape = salmonella_isolate_df_cleaned.shape
print("Updated DataFrame shape:", updated_shape)

Updated DataFrame shape: (8162, 17)

In [30]:
# Check the entire DataFrame for any remaining null values
# This will return the count of null values for each column in the DataFrame
null_values_df = salmonella_isolate_df_cleaned.isnull().sum()

# Display columns that still have null values, if any
null_values_df[null_values_df > 0]

Series([], dtype: int64)

In [31]:
# Assuming salmonella_isolate_df_cleaned is defined and contains the 'Age Group' column
# Print the counts of each age group
age_group_counts = salmonella_isolate_df_cleaned['Age Group'].value_counts()
age_group_counts

Age Group
20-29    1331
50-59    1027
30-39     966
40-49     933
0-4       856
10-19     842
60-69     822
70-79     549
5-9       524
80+       312
Name: count, dtype: int64

In [32]:
# Print the counts of each region in the 'Region' column
region_counts = salmonella_isolate_df_cleaned['Region Name'].value_counts()

# Display the counts
region_counts

Region Name
Region 5     1576
Region 4     1276
Region 3     1152
Region 9     1031
Region 2      981
Region 1      604
Region 6      521
Region 7      412
Region 10     317
Region 8      292
Name: count, dtype: int64

In [33]:
# Print the counts of each region in the 'Region' column
specimen_source_counts = salmonella_isolate_df_cleaned['Specimen Source'].value_counts()

# Display the counts
specimen_source_counts

Specimen Source
Stool           6975
Blood            601
Urine            356
Other            111
Not Given         48
Unknown           40
Wound             15
Abscess           12
CSF                2
Gall Bladder       2
Name: count, dtype: int64

In [34]:
# Rename all entries in 'Specimen Source' that are 'Not Given' to 'Unknown'
salmonella_isolate_df_cleaned['Specimen Source'] = salmonella_isolate_df_cleaned['Specimen Source'].replace('Not Given', 'Unknown')

# Display the updated counts for 'Specimen Source' to verify the change
updated_specimen_counts = salmonella_isolate_df_cleaned['Specimen Source'].value_counts()
updated_specimen_counts

Specimen Source
Stool           6975
Blood            601
Urine            356
Other            111
Unknown           88
Wound             15
Abscess           12
CSF                2
Gall Bladder       2
Name: count, dtype: int64

In [35]:
# Generate summary statistics for object columns
object_summary = salmonella_isolate_df_cleaned.describe(include=['object'])
object_summary

,Specimen ID,Region Name,Age Group,Specimen Source,AMP Concl,AUG Concl,AXO Concl,CHL Concl,CIP Concl,COT Concl,FIS Concl,FOX Concl,GEN Concl,NAL Concl,STR Concl,TET Concl
count,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162,8162
unique,8162,10,10,9,3,3,3,3,3,2,2,3,3,2,2,3
top,AM15266,Region 5,20-29,Stool,S,S,S,S,S,S,S,S,S,S,S,S
freq,1,1576,1331,6975,7859,8096,8139,8078,6962,8108,7993,8115,8145,6976,8020,7854

In [36]:
# Create the 'AR Level' column by counting the number of resistances (R) across all selected antibiotics
# This new feature allows for analysis of multi-antibiotic resistance levels
antibiotic_columns = [col for col in salmonella_isolate_df_cleaned.columns if col.endswith('Concl')]

salmonella_isolate_df_cleaned['AR Level'] = salmonella_isolate_df_cleaned[antibiotic_columns].apply(lambda row: row.str.count('R').sum(), axis=1)

# Sort AR Level counts in ascending order and display
mar_level_counts = salmonella_isolate_df_cleaned['AR Level'].value_counts().sort_index()
mar_level_counts

AR Level
0    6592
1    1271
2     110
3      71
4      73
5      29
6       6
7       4
8       3
9       3
Name: count, dtype: int64

In [37]:
salmonella_isolate_df_cleaned.head()

,Specimen ID,Data Year,Region Name,Age Group,Specimen Source,AMP Concl,AUG Concl,AXO Concl,CHL Concl,CIP Concl,COT Concl,FIS Concl,FOX Concl,GEN Concl,NAL Concl,STR Concl,TET Concl,AR Level
0,AM15266,2003,Region 5,30-39,Stool,S,S,S,I,I,S,S,S,S,R,S,S,1
1,AM43140,2010,Region 2,20-29,Stool,S,S,S,S,S,S,S,S,S,S,S,S,0
3,AM43324,2010,Region 9,40-49,Stool,S,S,S,S,I,S,S,S,S,R,S,S,1
4,AM29874,2006,Region 10,20-29,Stool,R,S,S,S,I,S,R,S,S,R,R,S,4
5,AM18769,2003,Region 2,5-9,Stool,S,S,S,S,S,S,S,S,S,S,S,S,0

In [38]:
# Save the DataFrame as a CSV file
salmonella_isolate_df_cleaned.to_csv('salmonella_isolate_data_cleaned.csv', index=False)

# Confirm that the file has been saved
import os
file_saved = os.path.isfile('salmonella_isolate_data_cleaned.csv')
file_saved

True

In [39]:
# Identify columns that end with 'Concl'
antibiotic_columns = [col for col in salmonella_isolate_df_cleaned.columns if col.endswith('Concl')]

# Group by Data Year and Region Name
grouped_data = salmonella_isolate_df_cleaned.groupby(['Data Year', 'Region Name'])[antibiotic_columns].agg(
    lambda x: (x == 'R').sum() / len(x) * 100
).reset_index()

# Rename columns to indicate percentage
grouped_data.columns = ['Data Year', 'Region Name'] + [f'{col.replace(" Concl", "")} Resistance Percentage' for col in antibiotic_columns]

# Format resistance percentage columns to 2 decimal places
for col in grouped_data.columns[2:]:  # Skip the first two columns (Data Year and Region Name)
    grouped_data[col] = grouped_data[col].round(2)

# Calculate total resistance by summing the resistance percentages
grouped_data['Total Resistance Percentage'] = grouped_data.iloc[:, 2:].sum(axis=1)

In [40]:
grouped_data

,Data Year,Region Name,AMP Resistance Percentage,AUG Resistance Percentage,AXO Resistance Percentage,CHL Resistance Percentage,CIP Resistance Percentage,COT Resistance Percentage,FIS Resistance Percentage,FOX Resistance Percentage,GEN Resistance Percentage,NAL Resistance Percentage,STR Resistance Percentage,TET Resistance Percentage,Total Resistance Percentage
0,2003,Region 1,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,11.11,0.00,0.00,11.11
1,2003,Region 10,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
2,2003,Region 2,6.90,0.0,0.0,0.00,0.0,0.00,3.45,0.0,3.45,0.00,6.90,0.00,20.70
3,2003,Region 3,2.08,0.0,0.0,0.00,0.0,0.00,4.17,0.0,0.00,0.00,0.00,2.08,8.33
4,2003,Region 4,7.69,0.0,0.0,2.56,0.0,2.56,0.00,0.0,0.00,7.69,2.56,2.56,25.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2023,Region 5,3.33,0.0,0.0,0.00,0.0,0.00,1.67,0.0,0.00,36.67,0.00,1.67,43.34
206,2023,Region 6,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,38.10,0.00,0.00,38.10
207,2023,Region 7,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,18.18,0.00,0.00,18.18
208,2023,Region 8,11.76,0.0,0.0,0.00,0.0,0.00,5.88,0.0,0.00,35.29,0.00,0.00,52.93
209,2023,Region 9,1.37,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,60.27,0.00,0.00,61.64

In [41]:
# Save the new DataFrame to a CSV file
output_file_path = 'salmonella_antibiotic_resistance_percentage.csv'
grouped_data.to_csv(output_file_path, index=False)

## Workflow Overview

> Data Loading: The dataset was loaded from the CDC National Antimicrobial Resistance Monitoring System (NARMS) to ensure reliable and comprehensive surveillance data.
>
> Data Wrangling:
> - Checking for Duplicates: Verified that no duplicates existed in the Specimen ID column, which serves as the unique identifier for each isolate.
> - Initial Exploration: Displayed the first few rows of the dataset to understand its structure and identify potential issues, such as missing values.
Removal of Redundant Columns: Columns deemed unnecessary for analysis, including those with a high proportion of missing values, were identified and removed, streamlining the dataset for further analysis.
Handling Missing Values:
> - Categorical Columns: Missing values in critical categorical columns (e.g., Age Group and Specimen Source) were filled with the mode to maintain data integrity.
Conclusion Columns: Missing entries in conclusion columns were imputed with 'X', indicating that breakpoints or epidemiological cutoff values were unavailable.
> - Excessive Missing Values: Columns with over 90% missing values were removed to focus on relevant features.
> - Data Type Verification: Data types for all columns were checked and ensured to be appropriate for analysis, making necessary conversions for compatibility with modeling techniques.
> - Creation of New Features: A new feature, AR Level, was derived by counting the number of antibiotic resistances across the dataset, providing a quantitative measure of multi-antibiotic resistance.
> - Summary Statistics: Summary statistics were generated to understand the distribution of numeric data, and the data was saved as a cleaned CSV file for future use.
>
> Resistance Calculation: The dataset was further processed to group data by year and region, calculating antibiotic resistance percentages and total resistance levels. This new dataframe was saved as a csv for further processing.
>
>By following these steps, we have prepared a clean, structured dataset ready for exploratory data analysis and predictive modeling, supporting the overall objectives of this project in understanding antibiotic resistance patterns in Salmonella Enteriditis.